
GET http://localhost:5000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUxMDc0ODAwLCJleHAiOjE3NTEwOTY0MDB9.t1ff0tzrAeIs7AUz_Li4KaoT7a27liSsOY9ZZPmqobM
###

GET http://localhost:5000/auth/hd_users

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "cntt2",
  "password": "123456",
  "coQuanId": 1
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "dlc",
  "password": "dlc"
}

###
POST http://localhost:5000/auth/resetUUID
Content-Type: application/json

{
  "username": "DiemLinhCo"
}

###

POST http://localhost:5000/QLHD/hopdong
Content-Type: application/json

{
  "SoVanBanNoiBo": "001/Z176-CNTT-HD"
}

###
GET http://localhost:5000/QLHD/lookup