
GET http://localhost:5000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUxMDMxMDQ1LCJleHAiOjE3NTEwNTI2NDV9.PlEb1xBy6_j4lw6HWOGFkvy_xA8r0QMfz2DKlhWHqZQ
###

GET http://localhost:5000/auth/hd_users

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "dlc",
  "password": "dlc"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "dlc",
  "password": "dlc"
}

###
POST http://localhost:5000/auth/resetUUID
Content-Type: application/json

{
  "username": "DiemLinhCo"
}