
GET http://localhost:5000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjA1MDYxNiwiZXhwIjoxNzUyMDcyMjE2fQ.Jk9hBv0i6AYfAypUKhoVWWC7c_OjtfIPNMOJDmgkEEE

###

GET https://nodeapi.z76.vn/auth/hd_users

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "cntt2",
  "password": "123456",
  "coQuanId": 1
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "dlc",
  "password": "dlc"
}

###
POST http://localhost:5000/auth/resetUUID
Content-Type: application/json

{
  "username": "DiemLinhCo"
}

###

POST http://localhost:5000/QLHD/hopdong
Content-Type: application/json

{
  "SoVanBanNoiBo": "001/Z176-CNTT-HD"
}

###
GET http://localhost:5000/QLHD/lookup